from setuptools import setup, find_packages

setup(
    name="NetWise",
    version="1.0.0",
    description="A comprehensive library for network and Wi-Fi security analysis. Here you can also check for your computer's performance, safety, scan your ifles and find specs.There are some features for backups to.",
    author="Hasan KAYAN",
    author_email="hasankayanformal@gmail.com",
    author_website="https://www.hasankayan.com",
    author_github="https://github.com/hasan-kayan",
    packages=find_packages(where='lib'),
    package_dir={'': 'lib'},
     install_requires=[
        "altgraph==0.17.4",
        "attrs==24.2.0",
        "beautifulsoup4==4.12.3",
        "blinker==1.8.2",
        "certifi==2024.7.4",
        "charset-normalizer==3.3.2",
        "click==8.1.7",
        "et-xmlfile==1.1.0",
        "Flask==3.0.3",
        "h11==0.14.0",
        "idna==3.7",
        "itsdangerous==2.2.0",
        "Jinja2==3.1.4",
        "keyboard==0.13.5",
        "macholib==1.16.3",
        "MarkupSafe==2.1.5",
        "openpyxl==3.1.5",
        "outcome==1.3.0.post0",
        "packaging==24.1",
        "pillow==10.4.0",
        "psutil==6.0.0",
        "pyinstaller==6.10.0",
        "pyinstaller-hooks-contrib==2024.8",
        "PySocks==1.7.1",
        "python-dotenv==1.0.1",
        "requests==2.32.3",
        "scapy==2.5.0",
        "selenium==4.23.1",
        "setuptools==73.0.1",
        "sniffio==1.3.1",
        "sortedcontainers==2.4.0",
        "soupsieve==2.5",
        "trio==0.26.2",
        "trio-websocket==0.11.1",
        "typing_extensions==4.12.2",
        "urllib3==2.2.2",
        "webdriver-manager==4.0.2",
        "websocket-client==1.8.0",
        "Werkzeug==3.0.3",
        "wsproto==1.2.0",
    ],
)
